# Generated by Django 4.2.4 on 2023-08-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('pub_date',)},
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(default=123, max_length=140, verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
