# Generated by Django 4.2.3 on 2023-08-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_post_options_post_text'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='read',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unqiue_post'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'blog'), name='unqiue_subscription'),
        ),
    ]
